final List<Map<String, dynamic>> eventTypes = [
  {
    'title': 'Workshop',
    'items': [
      'Painting Workshop',
      'Sculpture Workshop',
      'Pottery Workshop',
      'Other Art Workshop',
      'Baking Workshop',
      'International Cuisine Workshop',
      'Vegan Cooking Workshop',
      'Other Cooking Workshop',
      'Creative Writing Workshop',
      'Poetry Workshop',
      'Screenwriting Workshop',
      'Other Writing Workshop',
      'Photography Workshop',
      'Dance Workshop',
      'Music Workshop',
      'Other Workshop',
    ],
  },
  {
    'title': 'Seminar',
    'items': [
      'Entrepreneurship Seminar',
      'Marketing Seminar',
      'Leadership Seminar',
      'Other Business Seminar',
      'Nutrition Seminar',
      'Mental Health Seminar',
      'Fitness Seminar',
      'Other Health Seminar',
      'STEM Seminar',
      'Language Learning Seminar',
      'History Seminar',
      'Other Educational Seminar',
      'AI Seminar',
      'Cybersecurity Seminar',
      'Software Development Seminar',
      'Other Technology Seminar',
      'Environmental Seminar',
      'Social Justice Seminar',
      'Financial Planning Seminar',
      'Other Seminar',
    ],
  },
  {
    'title': 'Concert',
    'items': [
      'Indie Rock Concert',
      'Classic Rock Concert',
      'Alternative Rock Concert',
      'Other Rock Concert',
      'Symphony Orchestra Concert',
      'Chamber Music Concert',
      'Opera Concert',
      'Other Classical Concert',
      'Smooth Jazz Concert',
      'Bebop Jazz Concert',
      'Jazz Fusion Concert',
      'Other Jazz Concert',
      'Pop Idol Concert',
      'Boy Band Concert',
      'Pop Rock Concert',
      'Other Pop Concert',
      'Country Concert',
      'Hip-Hop Concert',
      'EDM Concert',
      'Other Concert',
    ],
  },
  {
    'title': 'Exhibition',
    'items': [
      'Contemporary Art Exhibition',
      'Photography Exhibition',
      'Sculpture Exhibition',
      'Other Art Exhibition',
      'Technology Exhibition',
      'Natural History Exhibition',
      'Space Exploration Exhibition',
      'Other Science Exhibition',
      'Industry Trade Show',
      'Consumer Goods Exhibition',
      'Automotive Exhibition',
      'Other Trade Exhibition',
      'Wildlife Photography Exhibition',
      'Fashion Photography Exhibition',
      'Travel Photography Exhibition',
      'Other Photography Exhibition',
      'Craft Exhibition',
      'Design Exhibition',
      'Cultural Exhibition',
      'Other Exhibition',
    ],
  },
  {
    'title': 'Conference',
    'items': [
      'Research Conference',
      'Educational Conference',
      'Scientific Conference',
      'Other Academic Conference',
      'Startup Conference',
      'Corporate Conference',
      'Investment Conference',
      'Other Business Conference',
      'Developer Conference',
      'Tech Innovation Conference',
      'Cybersecurity Conference',
      'Other Tech Conference',
      'Medical Conference',
      'Wellness Conference',
      'Public Health Conference',
      'Other Health Conference',
      'Environmental Conference',
      'Social Impact Conference',
      'Creative Arts Conference',
      'Other Conference',
    ],
  },
  {
    'title': 'Festival',
    'items': [
      'Jazz Festival',
      'Rock Festival',
      'Electronic Music Festival',
      'Other Music Festival',
      'Street Food Festival',
      'Wine and Cheese Festival',
      'Vegan Food Festival',
      'Other Food Festival',
      'Independent Film Festival',
      'Documentary Film Festival',
      'Animation Film Festival',
      'Other Film Festival',
      'Heritage Festival',
      'Folk Festival',
      'Multicultural Festival',
      'Other Cultural Festival',
      'Literature Festival',
      'Comedy Festival',
      'Dance Festival',
      'Other Festival',
    ],
  },
  {
    'title': 'Competition',
    'items': [
      'Soccer Tournament',
      'Basketball Championship',
      'Marathon',
      'Other Sports Competition',
      'Singing Competition',
      'Dance Competition',
      'Talent Show',
      'Other Talent Competition',
      'Esports Tournament',
      'Board Game Competition',
      'Card Game Tournament',
      'Other Gaming Competition',
      'Science Fair',
      'Math Olympiad',
      'Debate Competition',
      'Other Academic Competition',
      'Cooking Competition',
      'Art Competition',
      'Photography Competition',
      'Other Competition',
    ],
  },
  {
    'title': 'Birthday Party',
    'items': [
      'Themed Birthday Party',
      'Outdoor Adventure Party',
      'Indoor Play Center Party',
      'Other Children\'s Birthday Party',
      'Pool Party',
      'Movie Night Party',
      'Dance Party',
      'Other Teen Birthday Party',
      'Dinner Party',
      'Cocktail Party',
      'Themed Costume Party',
      'Other Adult Birthday Party',
      '1st Birthday Party',
      'Sweet 16 Party',
      '50th Birthday Party',
      'Other Milestone Birthday Party',
      'Surprise Birthday Party',
      'Virtual Birthday Party',
      'Destination Birthday Party',
      'Other Birthday Party',
    ],
  },
  {
    'title': 'Holiday Celebration',
    'items': [
      'Ugly Sweater Party',
      'Secret Santa Party',
      'Christmas Caroling Party',
      'Other Christmas Party',
      'Costume Party',
      'Haunted House Party',
      'Pumpkin Carving Party',
      'Other Halloween Party',
      'Community Egg Hunt',
      'Backyard Egg Hunt',
      'Indoor Egg Hunt',
      'Other Easter Egg Hunt',
      'Family Thanksgiving Dinner',
      'Friendsgiving Dinner',
      'Potluck Thanksgiving Dinner',
      'Other Thanksgiving Dinner',
      'New Year\'s Eve Party',
      'Valentine\'s Day Party',
      'Independence Day BBQ',
      'Other Holiday Celebration',
    ],
  },
  {
    'title': 'Family Reunion',
    'items': [
      'Park Picnic Reunion',
      'Beach Picnic Reunion',
      'Backyard Picnic Reunion',
      'Other Picnic Reunion',
      'Traditional BBQ Reunion',
      'Potluck BBQ Reunion',
      'Themed BBQ Reunion',
      'Other BBQ Reunion',
      'Beach Party Reunion',
      'Beach Games Reunion',
      'Beach Bonfire Reunion',
      'Other Beach Reunion',
      'Forest Camping Reunion',
      'Lakeside Camping Reunion',
      'RV Camping Reunion',
      'Other Camping Reunion',
      'Cruise Reunion',
      'Resort Reunion',
      'City Tour Reunion',
      'Other Family Reunion',
    ],
  },
  {
    'title': 'Anniversary Celebration',
    'items': [
      'Vow Renewal Ceremony',
      'Romantic Dinner',
      'Anniversary Party',
      'Other Wedding Anniversary',
      'Romantic Getaway',
      'Special Date Night',
      'Personalized Gift Exchange',
      'Other Relationship Anniversary',
      'Company Party',
      'Employee Appreciation Event',
      'Client Appreciation Event',
      'Other Business Anniversary',
      'Friendship Anniversary',
      'Club Anniversary',
      'Community Anniversary',
      'Other Anniversary Celebration',
    ],
  },
  {
    'title': 'Baby Shower',
    'items': [
      'Themed Baby Shower',
      'Brunch Baby Shower',
      'Afternoon Tea Baby Shower',
      'Other Traditional Baby Shower',
      'Balloon Pop Reveal',
      'Cake Cutting Reveal',
      'Confetti Cannon Reveal',
      'Other Gender Reveal Party',
      'Casual Sip and See',
      'Themed Sip and See',
      'Outdoor Sip and See',
      'Other Sip and See Party',
      'Virtual Baby Shower',
      'Co-ed Baby Shower',
      'Diaper Party',
      'Other Baby Shower',
    ],
  },
  {
    'title': 'Graduation Party',
    'items': [
      'Backyard BBQ Graduation Party',
      'Pool Graduation Party',
      'Themed Graduation Party',
      'Other High School Graduation Party',
      'Formal Graduation Dinner',
      'Outdoor Graduation Celebration',
      'Graduation Trip',
      'Other College Graduation Party',
      'Playdate Graduation Party',
      'Park Graduation Party',
      'Classroom Graduation Party',
      'Other Kindergarten Graduation Party',
      'Trade School Graduation',
      'Military Graduation',
      'Online Course Graduation',
      'Other Graduation Party',
    ],
  },
  {
    'title': 'Seasonal Event',
    'items': [
      'Poolside BBQ',
      'Beach BBQ',
      'Backyard BBQ',
      'Other Summer BBQ',
      'Pumpkin Patch Visit',
      'Apple Picking Event',
      'Hayride and Bonfire',
      'Other Fall Harvest Festival',
      'Snowman Building Contest',
      'Ice Skating Party',
      'Hot Cocoa Bar Party',
      'Other Winter Wonderland Party',
      'Flower Planting Party',
      'Easter Egg Hunt',
      'Outdoor Tea Party',
      'Other Spring Garden Party',
      'Spring Cleaning Party',
      'Summer Solstice Celebration',
      'Autumn Equinox Gathering',
      'Other Seasonal Event',
    ],
  },
  {
    'title': 'Religious Celebration',
    'items': [
      'Church Baptism Ceremony',
      'Home Baptism Celebration',
      'Outdoor Baptism Event',
      'Other Baptism',
      'Bar/Bat Mitzvah',
      'Synagogue',
    ],
  },
];
