final List<Map<String, dynamic>> servicesOffered = [
  {
    'title': 'Photographer',
    'items': [
      'Portrait Photographer',
      'Event Photographer',
      'Wildlife Photographer',
      'Fashion Photographer',
      'Sports Photographer',
      'Travel Photographer',
      'Fine Art Photographer',
      'Architectural Photographer',
      'Drone Photographer',
      'Other Photographer',
    ],
  },
  {
    'title': 'Videographer',
    'items': [
      'Event Videographer',
      'Documentary Videographer',
      'Commercial Videographer',
      'Wedding Videographer',
      'Music Video Director',
      'Film Director',
      'Cinematographer',
      'Drone Videographer',
      'Live Stream Producer',
      'Other Videographer',
    ],
  },
  {
    'title': 'Musician',
    'items': [
      'Singer',
      'Instrumentalist',
      'Composer',
      'DJ',
      'Music Producer',
      'Band Member',
      'Orchestra Member',
      'Sound Designer',
      'Beat Maker',
      'Other Musician',
    ],
  },
  {
    'title': 'Artist',
    'items': [
      'Painter',
      'Sculptor',
      'Digital Artist',
      'Illustrator',
      'Muralist',
      'Printmaker',
      'Mixed Media Artist',
      'NFT Artist',
      'Other Artist',
    ],
  },
  {
    'title': 'Performer',
    'items': [
      'Actor',
      'Comedian',
      'Magician',
      'Circus Performer',
      'Street Performer',
      'Music Performer',
      'Dancer',
      'Performance Artist',
      'Other Performer',
    ],
  },
  {
    'title': 'Animator',
    'items': [
      '2D Animator',
      '3D Animator',
      'Stop Motion Animator',
      'Motion Graphics Designer',
      'Visual Effects Artist',
      'VR/AR Animator',
      'Other Animator',
    ],
  },
  {
    'title': 'Craftsperson',
    'items': [
      'Woodworker',
      'Metalworker',
      'Jewelry Maker',
      'Textile Artist',
      'Ceramist',
      'Glassblower',
      'Leatherworker',
      'Other Craftsperson',
    ],
  },
  {
    'title': 'Makeup Artist',
    'items': [
      'Bridal Makeup Artist',
      'Fashion Makeup Artist',
      'Special Effects Makeup Artist',
      'Film/TV Makeup Artist',
      'Editorial Makeup Artist',
      'Cosplay Makeup Artist',
      'Other Makeup Artist',
    ],
  },
  {
    'title': 'Stylist',
    'items': [
      'Fashion Stylist',
      'Hair Stylist',
      'Personal Stylist',
      'Editorial Stylist',
      'Wardrobe Consultant',
      'Virtual Stylist',
      'Other Stylist',
    ],
  },
  {
    'title': 'Voice Actor',
    'items': [
      'Animation Voice Actor',
      'Commercial Voice Actor',
      'Audiobook Narrator',
      'Video Game Voice Actor',
      'Podcast Host',
      'AI Voice Actor',
      'Other Voice Actor',
    ],
  },
  {
    'title': 'Technologist',
    'items': [
      'App Developer',
      'Web Developer',
      'Game Developer',
      'AI Specialist',
      'Data Scientist',
      'Blockchain Developer',
      'Other Technologist',
    ],
  },
  {
    'title': 'Digital Content Creator',
    'items': [
      'YouTuber',
      'Vlogger',
      'Podcaster',
      'Social Media Content Creator',
      'Influencer',
      'Streamer',
      'Blogger',
      'TikTok Creator',
      'Other Digital Content Creator',
    ],
  },
  {
    'title': 'Model',
    'items': [
      'Fashion Model',
      'Commercial Model',
      'Fitness Model',
      'Runway Model',
      'Print Model',
      'Glamour Model',
      'Plus-Size Model',
      'Alternative Model',
      'Boudoir Model',
      'OnlyFans [Adult Content] Model',
      'Other Model',
    ],
  }
];
